/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;

/**
 * Clase de tipo jDialog en el cual muestra al usuario tres bloques.
 * El primer bloque corresponde al primer degradado, que podrá elegir
 * seis colores: rojo, verde, azul, amarillo, blanco, negro.
 * El segundo bloque corresponde con el segundo color para el degradado
 * con los mismos seis colores mencionados para el primer bloque. El tercer
 * bloque corresponde con la dirección del degradado, si será horizontal
 * o vertical.
 * La clase almacena la información enviada por el usuario para que posteriormente
 * la clase que lo solicite pueda obtener la información.
 * Si el usuario no introduce datos en los tres bloques y pulsa el botón aceptar,
 * la ventana no se cerrará.
 * 
 * @author Antonio Manuel Fernández Cantos
 */
public class OpcionDegradado extends javax.swing.JDialog {

    /**
     * Atributo de clase de tipo int que se indentifica con la opción vertical
     * del tercer bloque.
     */
    public static final int VERTICAL = 1;
    
    /**
     * Atributo de clase de tipo int que se identifica con la opción horizontal del
     * tercer bloque.
     */
    public static final int HORIZONTAL = 2;
    
    /**
     * Atributo de tipo entero que almacena el tipo elegido por el usuario en el
     * tercer bloque.
     */
    private int tipo;
    
    /**
     * Atributo de tipo Color que almacena el color del primer bloque introducido
     * por el usuario.
     */
    private Color color1;
    
    /**
     * Atributo de tipo Color que almacena el color del segundo bloque introducido
     * por el usuario.
     */
    private Color color2;
    
    /**
     * Atributo de tipo boolean que almacena si el usuario a pulsado aceptar.
     */
    private boolean aceptar;
    
    /**
     * Constructor de la clase en la cual se inicializan los atributos de la clase
     * por defecto.
     */
    public OpcionDegradado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipo=1; // Vertical por defecto.
        // Por defecto tenemos la opción vertical activada.
        this.botonVertical.setSelected(true);
        // Botón aceptar a false.
        aceptar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoColores1 = new javax.swing.ButtonGroup();
        grupoColores2 = new javax.swing.ButtonGroup();
        opcVerticalHorizontal = new javax.swing.ButtonGroup();
        panelInformacion = new javax.swing.JPanel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        panelRojo = new javax.swing.JPanel();
        rojo1 = new javax.swing.JRadioButton();
        rojo2 = new javax.swing.JRadioButton();
        panelNegro = new javax.swing.JPanel();
        negro1 = new javax.swing.JRadioButton();
        negro2 = new javax.swing.JRadioButton();
        panelVerde = new javax.swing.JPanel();
        verde1 = new javax.swing.JRadioButton();
        verde2 = new javax.swing.JRadioButton();
        panelAzul = new javax.swing.JPanel();
        azul1 = new javax.swing.JRadioButton();
        azul2 = new javax.swing.JRadioButton();
        panelBlanco = new javax.swing.JPanel();
        blanco1 = new javax.swing.JRadioButton();
        blanco2 = new javax.swing.JRadioButton();
        panelAmarillo = new javax.swing.JPanel();
        amarillo1 = new javax.swing.JRadioButton();
        amarillo2 = new javax.swing.JRadioButton();
        panelOpc = new javax.swing.JPanel();
        etiquetaOpciones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonVertical = new javax.swing.JRadioButton();
        bontonHorizontal = new javax.swing.JRadioButton();
        panelBotonAceptar = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new java.awt.GridLayout(9, 1));

        panelInformacion.setLayout(new java.awt.GridLayout(1, 0));

        etiqueta1.setText("Color 1:");
        panelInformacion.add(etiqueta1);

        etiqueta2.setText("Color 2:");
        panelInformacion.add(etiqueta2);

        getContentPane().add(panelInformacion);

        panelRojo.setLayout(new java.awt.GridLayout(1, 0));

        grupoColores1.add(rojo1);
        rojo1.setText("Rojo");
        rojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo1ActionPerformed(evt);
            }
        });
        panelRojo.add(rojo1);

        grupoColores2.add(rojo2);
        rojo2.setText("Rojo");
        rojo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojo2ActionPerformed(evt);
            }
        });
        panelRojo.add(rojo2);

        getContentPane().add(panelRojo);

        panelNegro.setLayout(new java.awt.GridLayout(1, 0));

        grupoColores1.add(negro1);
        negro1.setText("Negro");
        negro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro1ActionPerformed(evt);
            }
        });
        panelNegro.add(negro1);

        grupoColores2.add(negro2);
        negro2.setText("Negro");
        negro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negro2ActionPerformed(evt);
            }
        });
        panelNegro.add(negro2);

        getContentPane().add(panelNegro);

        panelVerde.setLayout(new java.awt.GridLayout(1, 0));

        grupoColores1.add(verde1);
        verde1.setText("Verde");
        verde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde1ActionPerformed(evt);
            }
        });
        panelVerde.add(verde1);

        grupoColores2.add(verde2);
        verde2.setText("Verde");
        verde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verde2ActionPerformed(evt);
            }
        });
        panelVerde.add(verde2);

        getContentPane().add(panelVerde);

        panelAzul.setLayout(new java.awt.GridLayout(1, 0));

        grupoColores1.add(azul1);
        azul1.setText("Azul");
        azul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul1ActionPerformed(evt);
            }
        });
        panelAzul.add(azul1);

        grupoColores2.add(azul2);
        azul2.setText("Azul");
        azul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azul2ActionPerformed(evt);
            }
        });
        panelAzul.add(azul2);

        getContentPane().add(panelAzul);

        panelBlanco.setLayout(new java.awt.GridLayout(1, 0));

        grupoColores1.add(blanco1);
        blanco1.setText("Blanco");
        blanco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanco1ActionPerformed(evt);
            }
        });
        panelBlanco.add(blanco1);

        grupoColores2.add(blanco2);
        blanco2.setText("Blanco");
        blanco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanco2ActionPerformed(evt);
            }
        });
        panelBlanco.add(blanco2);

        getContentPane().add(panelBlanco);

        panelAmarillo.setLayout(new java.awt.GridLayout(1, 0));

        grupoColores1.add(amarillo1);
        amarillo1.setText("Amarillo");
        amarillo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo1ActionPerformed(evt);
            }
        });
        panelAmarillo.add(amarillo1);

        grupoColores2.add(amarillo2);
        amarillo2.setText("Amarillo");
        amarillo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarillo2ActionPerformed(evt);
            }
        });
        panelAmarillo.add(amarillo2);

        getContentPane().add(panelAmarillo);

        panelOpc.setLayout(new java.awt.GridLayout(1, 0));

        etiquetaOpciones.setText("Opción");
        panelOpc.add(etiquetaOpciones);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        opcVerticalHorizontal.add(botonVertical);
        botonVertical.setText("Vertical");
        botonVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerticalActionPerformed(evt);
            }
        });
        jPanel2.add(botonVertical);

        opcVerticalHorizontal.add(bontonHorizontal);
        bontonHorizontal.setText("Horizontal");
        bontonHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bontonHorizontalActionPerformed(evt);
            }
        });
        jPanel2.add(bontonHorizontal);

        panelOpc.add(jPanel2);

        getContentPane().add(panelOpc);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonAceptarLayout = new javax.swing.GroupLayout(panelBotonAceptar);
        panelBotonAceptar.setLayout(panelBotonAceptarLayout);
        panelBotonAceptarLayout.setHorizontalGroup(
            panelBotonAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonAceptarLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(botonAceptar)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        panelBotonAceptarLayout.setVerticalGroup(
            panelBotonAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonAceptarLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(botonAceptar))
        );

        getContentPane().add(panelBotonAceptar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que instancia el atributo color1 con el color rojo.
     * @param evt 
     */
    private void rojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo1ActionPerformed
        this.color1 = Color.red;
    }//GEN-LAST:event_rojo1ActionPerformed

    /**
     * Método que instancia el atributo color1 con el color negro.
     * @param evt 
     */
    private void negro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro1ActionPerformed
        this.color1 = Color.BLACK;
    }//GEN-LAST:event_negro1ActionPerformed
    /**
     * Método que instancia el atributo color1 con el color verde.
     * @param evt 
     */
    private void verde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde1ActionPerformed
        this.color1 = Color.green;
    }//GEN-LAST:event_verde1ActionPerformed

    /**
     * Método que instancia el atributo color1 con el color azul.
     * @param evt 
     */
    private void azul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul1ActionPerformed
       this.color1 = Color.blue;
    }//GEN-LAST:event_azul1ActionPerformed
    /**
     * Método que instancia el atributo color1 con el color blanco.
     * @param evt 
     */
    private void blanco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanco1ActionPerformed
        this.color1 = Color.white;
    }//GEN-LAST:event_blanco1ActionPerformed
    /**
     * Método que instancia el atributo color1 con el color amarillo.
     * @param evt 
     */
    private void amarillo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo1ActionPerformed
        this.color1 = Color.yellow;
    }//GEN-LAST:event_amarillo1ActionPerformed
    /**
     * Método que instancia el atributo color2 con el color rojo.
     * @param evt 
     */
    private void rojo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojo2ActionPerformed
        this.color2 = Color.red;
    }//GEN-LAST:event_rojo2ActionPerformed
    /**
     * Método que instancia el atributo color2 con el color negro.
     * @param evt 
     */
    private void negro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negro2ActionPerformed
        this.color2 = Color.black;
    }//GEN-LAST:event_negro2ActionPerformed
    /**
     * Método que instancia el atributo color2 con el color verde.
     * @param evt 
     */
    private void verde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verde2ActionPerformed
        this.color2 = Color.green;
    }//GEN-LAST:event_verde2ActionPerformed
    /**
     * Método que instancia el atributo color2 con el color azul.
     * @param evt 
     */
    private void azul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azul2ActionPerformed
        this.color2 = Color.blue;
    }//GEN-LAST:event_azul2ActionPerformed
    /**
     * Método que instancia el atributo color2 con el color blanco.
     * @param evt 
     */
    private void blanco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanco2ActionPerformed
        this.color2 = Color.white;
    }//GEN-LAST:event_blanco2ActionPerformed
    /**
     * Método que instancia el atributo color2 con el color amarillo.
     * @param evt 
     */
    private void amarillo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarillo2ActionPerformed
        this.color2 = Color.yellow;
    }//GEN-LAST:event_amarillo2ActionPerformed

    /**
     * Método que instancia el atributo tipo con la opción vertical.
     * @param evt 
     */
    private void botonVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerticalActionPerformed
        this.tipo = OpcionDegradado.VERTICAL;
    }//GEN-LAST:event_botonVerticalActionPerformed

    /**
     * Método que instancia el atributo tipo con la opción horizontal.
     * @param evt 
     */
    private void bontonHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bontonHorizontalActionPerformed
        this.tipo = OpcionDegradado.HORIZONTAL;
    }//GEN-LAST:event_bontonHorizontalActionPerformed

    /**
     * Método que pone como verdadero el atributo booleano aceptar si se cumple que
     * tanto el color1 como color2 han sido instanciados.
     * Se desactiva la ventana en caso de que se cumpla lo anterior.
     * @param evt 
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        
        if(this.color1 != null && this.color2 != null){
            this.setVisible(false);
            this.aceptar = true;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * 
     * @return Devuelve el valor del atributo color1. De tipo Color.
     */
    public Color getColor1(){
        return this.color1;
    }
    
    /**
     * 
     * @return Devuelve el valor del atributo color2. De tipo Color. 
     */
    public Color getColor2(){
        return this.color2;
    }
    
    /**
     * 
     * @return Devuelve el valor del atributo tipo. De tipo entero. 
     */
    public int getTipo(){
        return this.tipo;
    }
    
    /**
     * 
     * @return Devuelve el valor del atributo aceptar. De tipo boolean.
     */
    public boolean getAceptar(){
        return this.aceptar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amarillo1;
    private javax.swing.JRadioButton amarillo2;
    private javax.swing.JRadioButton azul1;
    private javax.swing.JRadioButton azul2;
    private javax.swing.JRadioButton blanco1;
    private javax.swing.JRadioButton blanco2;
    private javax.swing.JRadioButton bontonHorizontal;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JRadioButton botonVertical;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiquetaOpciones;
    private javax.swing.ButtonGroup grupoColores1;
    private javax.swing.ButtonGroup grupoColores2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton negro1;
    private javax.swing.JRadioButton negro2;
    private javax.swing.ButtonGroup opcVerticalHorizontal;
    private javax.swing.JPanel panelAmarillo;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelBotonAceptar;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelNegro;
    private javax.swing.JPanel panelOpc;
    private javax.swing.JPanel panelRojo;
    private javax.swing.JPanel panelVerde;
    private javax.swing.JRadioButton rojo1;
    private javax.swing.JRadioButton rojo2;
    private javax.swing.JRadioButton verde1;
    private javax.swing.JRadioButton verde2;
    // End of variables declaration//GEN-END:variables
}
