/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 * Clase que almacena la información del nombre del programa, autor, versión
 * y correo para mostrarla por pantalla al usuario.
 * 
 * @author Antonio Manuel Fernández Cantos
 */
public class VentanaAcercaDe extends javax.swing.JDialog {

    /**
     * Constructor de la clase, inicia los valores por defecto.
     */
    public VentanaAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePrograma = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        nombreAutor = new javax.swing.JLabel();
        correo1 = new javax.swing.JLabel();
        correo2 = new javax.swing.JLabel();
        panelBoton = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        nombrePrograma.setText("Programa: Sistemas Multimedia Proyecto Final");
        getContentPane().add(nombrePrograma);

        version.setText("Versión: 2.0");
        getContentPane().add(version);

        nombreAutor.setText("Autor: Antonio Manuel Fernández Cantos");
        getContentPane().add(nombreAutor);

        correo1.setText("Correo: antkk10@correo.ugr.es");
        getContentPane().add(correo1);

        correo2.setText("Correo2: antoniomfc90@gmail.com");
        getContentPane().add(correo2);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonLayout = new javax.swing.GroupLayout(panelBoton);
        panelBoton.setLayout(panelBotonLayout);
        panelBotonLayout.setHorizontalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(botonAceptar)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        panelBotonLayout.setVerticalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAceptar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(panelBoton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que ocula esta ventana de la vista del usuario.
     * @param evt 
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel correo1;
    private javax.swing.JLabel correo2;
    private javax.swing.JLabel nombreAutor;
    private javax.swing.JLabel nombrePrograma;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
