/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 * Clase que se usa para obtener el ancho y el alto del lienzo donde podrá dibujar el usuario.
 * Los valores son inicializados por el usuario en la ventana de diálogo y son almacenados
 * para su posterior utilización en la ventana interna imagen.
 * @author Antonio Manuel Fernández Cantos
 */
public class ventanaSeleccionTam extends javax.swing.JDialog {

    /**
     * Corresponde al ancho del lienzo introducido por el usuario.
     */
    private int ancho;
    /**
     * Corresponde al alto del lienzo introducido por el usuario.
     */
    private int alto;
    /**
     * Indica si el usuario ha pulstado aceptar en la ventana de diálogo.
     */
    private boolean aceptar;
    /**
     * Constructor de la clase en la cual inicializa los valores por defecto.
     * Ancho y alto tienen valor 300.
     */
    public ventanaSeleccionTam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ancho = 300;
        alto = 300;
        aceptar=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraAncho = new javax.swing.JPanel();
        etiquetaAncho = new javax.swing.JLabel();
        spinnerAncho = new javax.swing.JSpinner();
        barraAlto = new javax.swing.JPanel();
        etiquetaAlto = new javax.swing.JLabel();
        spinnerAlto = new javax.swing.JSpinner();
        barraBoton = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(180, 200));
        setMinimumSize(new java.awt.Dimension(180, 200));
        setPreferredSize(new java.awt.Dimension(180, 200));
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        barraAncho.setMaximumSize(new java.awt.Dimension(32767, 40));
        barraAncho.setMinimumSize(new java.awt.Dimension(200, 40));
        barraAncho.setLayout(new java.awt.GridLayout(1, 2));

        etiquetaAncho.setText(" Ancho");
        barraAncho.add(etiquetaAncho);

        spinnerAncho.setModel(new javax.swing.SpinnerNumberModel(300, 200, 2000, 1));
        spinnerAncho.setMaximumSize(new java.awt.Dimension(100, 100));
        spinnerAncho.setMinimumSize(new java.awt.Dimension(100, 100));
        spinnerAncho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAnchoStateChanged(evt);
            }
        });
        barraAncho.add(spinnerAncho);

        getContentPane().add(barraAncho);

        barraAlto.setMaximumSize(new java.awt.Dimension(32767, 40));
        barraAlto.setMinimumSize(new java.awt.Dimension(200, 40));
        barraAlto.setPreferredSize(new java.awt.Dimension(400, 400));
        barraAlto.setLayout(new java.awt.GridLayout(1, 2));

        etiquetaAlto.setText(" Alto");
        barraAlto.add(etiquetaAlto);

        spinnerAlto.setModel(new javax.swing.SpinnerNumberModel(300, 200, 2000, 1));
        spinnerAlto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAltoStateChanged(evt);
            }
        });
        barraAlto.add(spinnerAlto);

        getContentPane().add(barraAlto);

        botonAceptar.setText("Aceptar");
        botonAceptar.setMaximumSize(new java.awt.Dimension(30, 30));
        botonAceptar.setMinimumSize(new java.awt.Dimension(30, 30));
        botonAceptar.setPreferredSize(new java.awt.Dimension(30, 30));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraBotonLayout = new javax.swing.GroupLayout(barraBoton);
        barraBoton.setLayout(barraBotonLayout);
        barraBotonLayout.setHorizontalGroup(
            barraBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraBotonLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        barraBotonLayout.setVerticalGroup(
            barraBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraBotonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(barraBoton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Obtiene el valor del ancho del lienzo introducido por el usuario.
     * @param evt 
     */
    private void spinnerAnchoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAnchoStateChanged
        this.ancho = (int) this.spinnerAncho.getValue();
    }//GEN-LAST:event_spinnerAnchoStateChanged

    /**
     * obtiene el valor del alto del lienzo introducido por el usuario.
     * @param evt 
     */
    private void spinnerAltoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAltoStateChanged
        this.alto = (int) this.spinnerAlto.getValue();
    }//GEN-LAST:event_spinnerAltoStateChanged

    /**
     * Método que pone como verdadero el atributo aceptar cuando el usuario pulsa el botón aceptar.
     * @param evt 
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.aceptar=true;
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * 
     * @return Devuelve el ancho del lienzo introducido por el usuario. 
     */
    public int getAncho(){
        return this.ancho;
    }
    
    /**
     * 
     * @return Devuelve el alto del lienzo introducido por el usuario. 
     */
    public int getAlto(){
        return this.alto;
    }
    
    /**
     * 
     * @return Devuelve si el usuario ha pulsado el botón aceptar. 
     */
    public boolean getBotonAceptar(){
        return this.aceptar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraAlto;
    private javax.swing.JPanel barraAncho;
    private javax.swing.JPanel barraBoton;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel etiquetaAlto;
    private javax.swing.JLabel etiquetaAncho;
    private javax.swing.JSpinner spinnerAlto;
    private javax.swing.JSpinner spinnerAncho;
    // End of variables declaration//GEN-END:variables
}
